### ISSUE TITLE
Permlinks Via Short UUIDs

### ISSUE THREAD

**Issue by gennyble** [gennyble/nyble.dev#1]
While I greatly adore the "link home and encourage exploration", I also adore not killing links. So here's an idea.

`https://nyble.dev/permlink-0ea835/home.html`

I think you might be able to see the pattern, but I'll describe it in more detail.

The first component above the root starts `permlink-` indicating it as such, and the `0ea835` is a short kind-of UUID for that page. Maybe it can be the first 3 bytes (as hex, 6 characters) of the sha256 hash of the original path, or maybe it's just 6 random url-allowed characters.

You can see that `/home.html` is next. That is purely cosmetic and for the user. You could leave it off, but it's a good indication of where the link is thinking it goes.

**Comment by novedevo** [comment]
Might `permalink` be a better phrase than `permlink`? It's more standard across the web, IME.

**Comment by gennyble** [comment]
Ah, I couldn't remember whether it was perma- or perm-.

Interesting that the portmanteau-originator took the A from permanent as it seems to cross a syllable boundary. I do think I prefer permlink, but if permalink is more standard than it's probably the right move, thanks!

**Comment by novedevo** [comment]
It works better phonetically, I think. Permalink, in my dialect, is pronounced along the lines of /ˈpɝmə.lɪŋk/ (unsure about the rhotic); the schwa between `m` and `l` kinda gets added regardless, the /pɝml/ consonant cluster isn't eminently pronounceable in English. An e would also signify a schwa in that position, but if you're adding a vowel anyway, it may as well be from one of the portmanteau'd words.

**Comment by gennyble** [comment]
i went with `keeplink` because i don't like the "forever" implication of permanent. see: https://nyble.dev/keeplink/sillygifs.html
